// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/25/2026, 5:45:12 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/san/Documents/Norton/Software_Development/year3/semester2/advance mobile app/assignment/librarain_web_admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/san/Documents/Norton/Software_Development/year3/semester2/advance mobile app/assignment/librarain_web_admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/san/Documents/Norton/Software_Development/year3/semester2/advance mobile app/assignment/librarain_web_admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/san/Documents/Norton/Software_Development/year3/semester2/advance mobile app/assignment/librarain_web_admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/san/Documents/Norton/Software_Development/year3/semester2/advance mobile app/assignment/librarain_web_admin/plugins/**/*.{js,ts,mjs}","/Users/san/Documents/Norton/Software_Development/year3/semester2/advance mobile app/assignment/librarain_web_admin/composables/**/*.{js,ts,mjs}","/Users/san/Documents/Norton/Software_Development/year3/semester2/advance mobile app/assignment/librarain_web_admin/utils/**/*.{js,ts,mjs}","/Users/san/Documents/Norton/Software_Development/year3/semester2/advance mobile app/assignment/librarain_web_admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/san/Documents/Norton/Software_Development/year3/semester2/advance mobile app/assignment/librarain_web_admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/san/Documents/Norton/Software_Development/year3/semester2/advance mobile app/assignment/librarain_web_admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/san/Documents/Norton/Software_Development/year3/semester2/advance mobile app/assignment/librarain_web_admin/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;