// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/26/2026, 7:54:37 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/macme/Desktop/Drive D/Norton Semester ll/Advance Mobile App/librarain_web_admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macme/Desktop/Drive D/Norton Semester ll/Advance Mobile App/librarain_web_admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macme/Desktop/Drive D/Norton Semester ll/Advance Mobile App/librarain_web_admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macme/Desktop/Drive D/Norton Semester ll/Advance Mobile App/librarain_web_admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macme/Desktop/Drive D/Norton Semester ll/Advance Mobile App/librarain_web_admin/plugins/**/*.{js,ts,mjs}","/Users/macme/Desktop/Drive D/Norton Semester ll/Advance Mobile App/librarain_web_admin/composables/**/*.{js,ts,mjs}","/Users/macme/Desktop/Drive D/Norton Semester ll/Advance Mobile App/librarain_web_admin/utils/**/*.{js,ts,mjs}","/Users/macme/Desktop/Drive D/Norton Semester ll/Advance Mobile App/librarain_web_admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macme/Desktop/Drive D/Norton Semester ll/Advance Mobile App/librarain_web_admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/macme/Desktop/Drive D/Norton Semester ll/Advance Mobile App/librarain_web_admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/macme/Desktop/Drive D/Norton Semester ll/Advance Mobile App/librarain_web_admin/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;